- name: Install Git, Python and configure Nginx on Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Remove default nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create static homepage
      copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <!DOCTYPE html>
                    <html lang="en">
                    <head>
                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <title>Fancy Homepage</title>
                        <style>
                            body {
                                margin: 0;
                                font-family: 'Arial', sans-serif;
                                background-color: #f5f5f5;
                            }

                            .navbar {
                                background-color: #333;
                                overflow: hidden;
                            }

                            .navbar a {
                                float: left;
                                display: block;
                                color: #f2f2f2;
                                text-align: center;
                                padding: 14px 20px;
                                text-decoration: none;
                            }

                            .navbar a:hover {
                                background-color: #ddd;
                                color: black;
                            }

                            .hero {
                                background-image: url('https://via.placeholder.com/1500');
                                background-size: cover;
                                background-position: center;
                                height: 100vh;
                                color: white;
                                display: flex;
                                justify-content: center;
                                align-items: center;
                                text-align: center;
                            }

                            .hero h1 {
                                font-size: 4em;
                                margin: 0;
                            }

                            .hero p {
                                font-size: 1.5em;
                            }

                            .content {
                                padding: 20px;
                            }

                            .content h2 {
                                text-align: center;
                                color: #333;
                            }

                            .card {
                                background-color: white;
                                padding: 20px;
                                margin: 20px;
                                border-radius: 10px;
                                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
                                transition: 0.3s;
                            }

                            .card:hover {
                                box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
                            }

                            .card img {
                                max-width: 100%;
                                border-radius: 10px 10px 0 0;
                            }

                            .card h3 {
                                margin: 10px 0;
                                color: #333;
                            }

                            .card p {
                                color: #777;
                            }

                            .footer {
                                background-color: #333;
                                color: white;
                                text-align: center;
                                padding: 10px 0;
                                position: fixed;
                                width: 100%;
                                bottom: 0;
                            }
                        </style>
                    </head>
                    <body>
                        <div class="navbar">
                            <a href="#home">Home</a>
                            <a href="#services">Services</a>
                            <a href="#about">About</a>
                            <a href="#contact">Contact</a>
                        </div>

                        <div class="hero">
                            <div>
                                <h1>Fancy homepage for Franklin Okpako</h1>
                                <p>Your journey to excellence starts here</p>
                            </div>
                        </div>

                        <div class="content">
                            <h2>Our Services</h2>
                            <div class="card">
                                <img src="https://via.placeholder.com/400x200" alt="Service Image">
                                <h3>Service One</h3>
                                <p>Discover our amazing service that will help you achieve your goals.</p>
                            </div>
                            <div class="card">
                                <img src="https://via.placeholder.com/400x200" alt="Service Image">
                                <h3>Service Two</h3>
                                <p>Experience the best quality and dedication with our second service.</p>
                            </div>
                            <div class="card">
                                <img src="https://via.placeholder.com/400x200" alt="Service Image">
                                <h3>Service Three</h3>
                                <p>Join our community and benefit from our professional expertise.</p>
                            </div>
                        </div>

                        <div class="footer">
                            <p>&copy; 2024 Fancy Homepage. All rights reserved.</p>
                        </div>
                    </body>
                    </html>
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Ensure sites-available and sites-enabled directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      loop:
        - /etc/nginx/sites-available
        - /etc/nginx/sites-enabled

    - name: Create static site Nginx config
      copy:
        dest: /etc/nginx/sites-available/static-site-config
        content: |
          server {
              listen 80;

              location / {
                  root /usr/share/nginx/html;
                  index index.html;
              }
          }
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Enable website configuration
      file:
        src: /etc/nginx/sites-available/static-site-config
        dest: /etc/nginx/sites-enabled/static-site-config
        state: link

    - name: Ensure Nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes
