name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-playbooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup SSH
        run: |
          eval $(ssh-agent -s)
          mkdir -p $HOME/.ssh

          # Write private key preserving newlines
          printf "%s\n" "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

          # Write known_hosts
          printf "%s\n" "${{ secrets.SSH_KNOWN_HOSTS }}" > $HOME/.ssh/known_hosts
          chmod 644 $HOME/.ssh/known_hosts

          # Debug key format
          echo "===== SSH key head ====="
          head -5 $HOME/.ssh/id_rsa
          echo "===== SSH key tail ====="
          tail -2 $HOME/.ssh/id_rsa

      - name: Test SSH connection
        run: |
          ssh -i $HOME/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              ubuntu@3.90.1.31 "echo 'SSH connection successful'"

      - name: Test Ansible connectivity
        run: ansible -i hosts.yml all -m ping

      - name: Run Ansible playbook
        run: ansible-playbook -i hosts.yml ansible-pb.yml
