name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Setup SSH 
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh/
          touch /home/runner/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> /home/runner/.ssh/known_hosts
          
      - name: Test SSH connection (optional)
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@184.73.113.226 "echo 'SSH connection successful'"
          
      - name: Run Ansible playbook
        shell: bash 
        run: ansible-playbook -i hosts.yml ansible-pb.yml
