name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-playbooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup SSH
        run: |
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh/

          # Write private key (preserve newlines)
          cat <<'EOF' >/home/runner/.ssh/id_rsa
${{ secrets.SSH_KEY }}
EOF
          chmod 600 /home/runner/.ssh/id_rsa

          # Write known_hosts
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > /home/runner/.ssh/known_hosts
          chmod 644 /home/runner/.ssh/known_hosts

          # Debug key format
          echo "===== SSH key head ====="
          head -5 /home/runner/.ssh/id_rsa
          echo "===== SSH key tail ====="
          tail -2 /home/runner/.ssh/id_rsa

      - name: Test SSH connection
        run: |
          ssh -i /home/runner/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              ubuntu@184.73.113.226 "echo 'SSH connection successful'"

      - name: Test Ansible connectivity
        run: ansible -i hosts.yml all -m ping

      - name: Run Ansible playbook
        run: ansible-playbook -i hosts.yml ansible-pb.yml
